### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by wongdark2017** [dgpp-programer/dgpp_rocksdb_demo#1]
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/825081bc-b487-4905-b93e-1a83e5a1b7bb">
I ran the shell code you have been prvoided in readme file,but got this uint64 doesn't name a type error.

and my running environment list as follwing:
```
Linux c7292f746436 6.10.4-linuxkit #1 SMP Wed Oct  2 16:38:00 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

```

**Comment by dgpp-programer** [comment]
@wongdark2017 I compiled without any problems, perhaps your gcc too low? Please provide your gcc version, my gcc is 11.2.1
![image](https://github.com/user-attachments/assets/e2a40de5-78a5-4a6b-b172-7d31eefb3fa0)
![image](https://github.com/user-attachments/assets/400317f7-6156-406a-b713-d2914573fea2)

**Comment by wongdark2017** [comment]
> @wongdark2017 I compiled without any problems, perhaps your gcc too low? Please provide your gcc version, my gcc is 11.2.1 ![image](https://private-user-images.githubusercontent.com/73419024/381616538-e2a40de5-78a5-4a6b-b172-7d31eefb3fa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDAxMzAsIm5iZiI6MTczMDMzOTgzMCwicGF0aCI6Ii83MzQxOTAyNC8zODE2MTY1MzgtZTJhNDBkZTUtNzhhNS00YTZiLWIxNzItN2QzMWVlZmIzZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxNTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MGEyY2M4N2VjZGM4ODg5OTc1ZmI4ZWM0ZGQ5YmM5NGUzZDNhNGY5MjFiM2JjZDFlN2MyMDlkYTgxN2VlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fRTo1RE9FwKbY8UB4-lEMeKNofvIaIs08RM_y1ea4As) ![image](https://private-user-images.githubusercontent.com/73419024/381616773-400317f7-6156-406a-b713-d2914573fea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDAxMzAsIm5iZiI6MTczMDMzOTgzMCwicGF0aCI6Ii83MzQxOTAyNC8zODE2MTY3NzMtNDAwMzE3ZjctNjE1Ni00MDZhLWI3MTMtZDI5MTQ1NzNmZWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxNTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTc4ZGIxNzk4YjdhZmI3ZGUzNTJlZmVhZDNhNTgyMWNiYzNmMjY5NWQyNGQwODE4YWViZmMzMTQ0MjAxNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KMwzRSVNYETD8XVOIj1R1ywR9n0rIydo_aFSx0iK1kA)

Here is mine gcc --version and the cmake error I've met
<img width="723" alt="image" src="https://github.com/user-attachments/assets/37279e22-49b3-4b59-9252-cc48f2979228">

**Comment by dgpp-programer** [comment]
> > @wongdark2017 I compiled without any problems, perhaps your gcc too low? Please provide your gcc version, my gcc is 11.2.1 ![image](https://private-user-images.githubusercontent.com/73419024/381616538-e2a40de5-78a5-4a6b-b172-7d31eefb3fa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDAxMzAsIm5iZiI6MTczMDMzOTgzMCwicGF0aCI6Ii83MzQxOTAyNC8zODE2MTY1MzgtZTJhNDBkZTUtNzhhNS00YTZiLWIxNzItN2QzMWVlZmIzZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxNTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MGEyY2M4N2VjZGM4ODg5OTc1ZmI4ZWM0ZGQ5YmM5NGUzZDNhNGY5MjFiM2JjZDFlN2MyMDlkYTgxN2VlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fRTo1RE9FwKbY8UB4-lEMeKNofvIaIs08RM_y1ea4As) ![image](https://private-user-images.githubusercontent.com/73419024/381616773-400317f7-6156-406a-b713-d2914573fea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDAxMzAsIm5iZiI6MTczMDMzOTgzMCwicGF0aCI6Ii83MzQxOTAyNC8zODE2MTY3NzMtNDAwMzE3ZjctNjE1Ni00MDZhLWI3MTMtZDI5MTQ1NzNmZWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxNTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTc4ZGIxNzk4YjdhZmI3ZGUzNTJlZmVhZDNhNTgyMWNiYzNmMjY5NWQyNGQwODE4YWViZmMzMTQ0MjAxNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KMwzRSVNYETD8XVOIj1R1ywR9n0rIydo_aFSx0iK1kA)
> 
> Here is mine gcc --version and the cmake error I've met <img alt="image" width="723" src="https://private-user-images.githubusercontent.com/37199039/381797676-37279e22-49b3-4b59-9252-cc48f2979228.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDk0MzQsIm5iZiI6MTczMDM0OTEzNCwicGF0aCI6Ii8zNzE5OTAzOS8zODE3OTc2NzYtMzcyNzllMjItNDliMy00YjU5LTkyNTItY2M0OGYyOTc5MjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0MzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMTVhYjE1NzRhMWQ2MTQyNGRiZWY0OWY3MjQ3MTNlOTI4YzhkNDMyOWEwN2ZjZTNhZDIxNGQ0NGM1NzYzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TYjRtl2XGAaKqlHq5Wejt3_n2UyDpfQ0stybgrlWILY">

install gflag in advance

**Comment by wongdark2017** [comment]
I compile successfully when I set the gcc and g++ version as 11.
